### ISSUE TITLE
Patch for dhcpd release 4.4.1

### ISSUE THREAD

**Issue by scramatte** [hansliss/gluff#3]
Hello,

We still use your patch for many years now and it works well.
Can you publish patch for version 4.4.1 that is used in Debian 10?

Regards

**Comment by hansliss** [comment]
Hi!

I'll take a look and see what I can do! I'll get back to you soon.

/Hans

**Comment by hansliss** [comment]
I've added a patch for 4.4.1 now, but I have to point out that I have no means of testing this anymore. I'm fairly confident that it will work, since (1) it's essentially the patch for 4.3.5 applied with very few errors that were easily corrected, and (2) it compiled with no errors in my code.

**Comment by scramatte** [comment]
On vanilla  isc dhcp server source code I can apply the patch and compile without issue.
With debian isc-dhcp-server package It doesn't works. 

To be able to create a package with your patch I need to use dpath under debian.

It looks that some files are  missing with debian package source like Makefile.in  as seems that are created on the fly.

Can you told me which files needs to be patched :   dhcp.c , dhcpd.c   ?

Regards

**Comment by hansliss** [comment]
You can just read the patch file, it's fairly readable diff text.
The source/header files patched are
includes/dhcpd.h
server/dhcp.c
server/dhcpd.c

Also, the patch adds server/hl_ldb.c.

I just noticed that there's some junk in the patch that shouldn't be there. I'll remove it.
